language: java
jdk:
- oraclejdk8
script: mvn -fae -U -B clean install -Pwith-docs -Pcheck
after_success:
- chmod +x .travis/deploy-docs.sh && .travis/deploy-docs.sh
- curl -Ls https://git.io/deploy-maven-snapshot | bash
env:
  global:
  - SNAPSHOT_BRANCH: develop
cache: 
  directories:
  - $HOME/.m2
notifications:
  irc:
    channels:
    - chat.freenode.net#52north
    on_failure: always
